controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
lexik_jwt_authentication_token:
  path: /api/login
  controller: lexik_jwt_authentication.controller.token:__invoke
  methods: ['POST']
